<a href="https://colab.research.google.com/github/Sidra-g/Deep-Learning/blob/main/Basic_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [ ]:
# Generate some sample data
# Predict the next number in a sequence (e.g., 1, 2, 3 -> 4)
def generate_sequence(n_samples, seq_length):
    X, y = [], []
    for _ in range(n_samples):
        start = np.random.randint(0, 50)
        seq = np.arange(start, start + seq_length)
        X.append(seq[:-1])  # Input sequence
        y.append(seq[-1])  # Target value
    return np.array(X), np.array(y)

In [ ]:
X, y = generate_sequence(10, 5)
print(X)
print(y)

[[49 50 51 52]
 [ 3  4  5  6]
 [48 49 50 51]
 [43 44 45 46]
 [37 38 39 40]
 [29 30 31 32]
 [17 18 19 20]
 [41 42 43 44]
 [ 2  3  4  5]
 [17 18 19 20]]
[53  7 52 47 41 33 21 45  6 21]


In [ ]:
# Hyperparameters
n_samples = 1000
seq_length = 5  # Length of each sequence

# Prepare the data
X, y = generate_sequence(n_samples, seq_length)
X = X.reshape((n_samples, seq_length - 1, 1))  # Reshape for RNN input
y = y.reshape((n_samples, 1))


In [ ]:
X

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[48],
        [49],
        [50],
        [51]],

       ...,

       [[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[49],
        [50],
        [51],
        [52]],

       [[22],
        [23],
        [24],
        [25]]])

In [ ]:
# Build the RNN model
model = Sequential([
    SimpleRNN(50, activation='relu', input_shape=(seq_length - 1, 1)),
    Dense(1)  # Output layer
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=20, batch_size=32, verbose=1)

# Test the model on a new sequence
test_seq = np.array([30, 31, 32, 33]).reshape((1, seq_length - 1, 1))
predicted = model.predict(test_seq)
print(f"Input sequence: {test_seq.flatten()}")
print(f"Predicted next value: {predicted[0][0]}")

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1286.2823
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71.9368
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2132
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2742
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2030
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1882
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1131
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0959
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0019
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0353
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9546
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0487
Epoch 13/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9307
Epoch 14/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8609
Epoch 15/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8814
Epoch 16/20
32/32 ━━━━━━━━